In [3]:
file = open('../Data/01. name.txt', 'r', encoding='utf-8')
data = file.read()
print(data)
file.close()

토트넘
PSG
바이에른 윈헨
울버햄튼

In [ ]:
# 입력받아 쓰기 (write)

file = open('../Data/01. name.txt', 'w', encoding='utf-8')
while True:
  team = input('팀 : ')
  if not team:
    print('프로그램이 종료 됩니다.')
    break
  file.write(team + '\n')
file.close()

프로그램이 종료 됩니다.

In [ ]:
# 입력받아 쓰기 (append)

file = open('../Data/01. name.txt', 'a', encoding='utf-8')
while True:
  team = input('팀 : ')
  if not team:
    print('프로그램이 종료 됩니다.')
    break
  file.write(team + '\n')
file.close()

프로그램이 종료 됩니다.

In [18]:
import pandas as pd

df = pd.read_excel('../Data/01. my_grade.xlsx')
df.head()

   이름  1차 지필  2차 지필  수행 1  수행 2 등급
0  유비     92     88    93    95  A
1  관우     89     90    85    78  B
2  장비     71     84    67    70  C

In [44]:
# 새로운 정보 추가

import pandas as pd

df = pd.read_excel('../Data/01. club.xlsx')
df.head()
add_df = pd.DataFrame([{
  '학번' : 10512, 
  '이름' : '김하늘', 
  '학년' : 1, 
  '동아리' : 'AI 연구부', 
  '역할' : ' 부원'
  }])

new_df = pd.concat([df, add_df], ignore_index=True) #ignore_index=True 는 인덱스를 순서대로 정렬
new_df.to_excel('../Data/01. new_club.xlsx', index=False)
new_df.tail()

      학번   이름  학년     동아리   역할
0  10401  이민호   1  AI 연구부   부장
1  10405  박서연   1  AI 연구부   부원
2  10503  최지우   1  AI 연구부   부원
3  10512  김하늘   1  AI 연구부   부원